### PR TITLE
Deprecate Zapp

### PR DESCRIPTION
**Pull request by dfed**
cc @EricMuller22 @zachmargolis @puls

### CODE REVIEW

**Comment by dfed** [comment]
Once this is LGTM'd, I will close the outstanding issues and PRs

**Comment by dfed** [comment]
@bnickel @phatmann do you guys have an interest in taking ownership of this repo, rather than having me deprecate it? Would be happy to transfer it to kif-framework

**Comment by EricMuller22** [comment]
gorm

**Comment by phatmann** [comment]
Seems like an interesting project, but being 4 years old I shudder to think what it would take to get it up to date with KIF 3. I am having enough trouble keeping up with KIF as it is :-)

That said, moving it to kif-framework before deprecating it might make sense for archival purposes.

**Pull request closed without merging**
